### ISSUE TITLE
HTMLElement.rootElement is deprecated.

### ISSUE THREAD

**Issue by Tehnix** [atom-haskell/language-haskell-scoped#4]
The contents of `atom-text-editor` elements are no longer encapsulated
within a shadow DOM boundary. Please, stop using `rootElement` and access
the editor contents directly instead.
```
HTMLElement.rootElement (/Applications/Atom.app/Contents/Resources/app/src/text-editor-element.js:23:10)
hl (/Users/tehnix/.atom/packages/language-haskell-scoped/lib/language-haskell-scoped.coffee:46:42)
<unknown> (/Users/tehnix/.atom/packages/language-haskell-scoped/lib/language-haskell-scoped.coffee:64:24)
```

**Comment by lierdakil** [comment]
Thanks for reporting!

I guess this is as good a time as any to transition to Atom 1.19 API and get rid of horrible hackiness that was this package. So here we go, v0.1.0 released, which uses proper Atom API now (and also better regular expressions with Unicode support) :tada:
